using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Name.Terrain { 

    public class MarchingCubesGPU : MonoBehaviour {

        // Size of the voxel array for each dimension.
        const int voxelArrSize = 64;

        // Size of the buffer to hold the vertices.
        // This is the maximum number of vertices marching cubes can produce, 5 triangles for each voxel.
        const int vertexBufferSize = voxelArrSize * voxelArrSize * voxelArrSize * 3 * 5;

        // Compute shader.
        public ComputeShader marchingCubeCS;

        // GPU data buffers.
        ComputeBuffer cubeEdgeFlags;
        ComputeBuffer triangleConnectionTable;
        ComputeBuffer meshBuffer;

    	void Start () {

            // There are 8 threads that run per each group so voxel array size must be divisible by 8
            if(voxelArrSize % 8 != 0)
            {
                throw new System.ArgumentException("Voxel array size must be divisible by 8");
            }

            // Buffer to hold the vertices generated by marching cubes
            meshBuffer = new ComputeBuffer(vertexBufferSize, sizeof(float) * 7);

            // Clear all the mesh vertices to -1
            // Vertices that are generated will have a value of 1
            float[] val = new float[vertexBufferSize * 7];
            for(int i = 0; i < vertexBufferSize * 7; ++i)
            {
                val[i] = -1.0f;
            }
            meshBuffer.SetData(val);

            // Upload cube edges lookup table.
            cubeEdgeFlags = new ComputeBuffer(256, sizeof(int));
            cubeEdgeFlags.SetData(Terrain3DTables.EdgeTable);

            // Upload triangle connection lookup table.
            triangleConnectionTable = new ComputeBuffer(256 * 16, sizeof(int));
            triangleConnectionTable.SetData(Terrain3DTables.TriTable);

            // Set buffer and dispatch
            marchingCubeCS.SetBuffer(0, "_Buffer", meshBuffer);
            marchingCubeCS.SetBuffer(0, "_CubeEdgeFlags", cubeEdgeFlags);
            marchingCubeCS.SetBuffer(0, "_TriangleConnectionTable", triangleConnectionTable);

            // Dispatch
            marchingCubeCS.Dispatch(0, vertexBufferSize / 8, vertexBufferSize / 8, vertexBufferSize / 8);
    	}
    	
    	// Update is called once per frame
    	void Update () {
    		
    	}
    }

}
